### ISSUE TITLE
As an author, posts I make can be in CommonMark

### ISSUE THREAD

**Issue by HyZ7846** [CMPUT404W23T19/Socially-Distributed#7]

**Comment by HyZ7846** [comment]
I don't understand what does **CommonMark** mean.

**Comment by smitpatel2** [comment]
It's a plain text format for writing structured documents, based on formatting conventions from email and Usenet.

**Comment by HyZ7846** [comment]
Like Markdown?

**Comment by smitpatel2** [comment]
I think commonmark is a specific implementation of markdown, to make it more consistent.
